#include <GL/glut.h>

GLint GenPolycrankBaseList();
GLint GenPolycrankQ1List();
GLint GenPolycrankJointQ2Q1List();
GLint GenPolycrankQ2List();
GLint GenPolycrankJointQ3Q2List();
GLint GenPolycrankQ3List();
GLint GenPolycrankJointQ4Q3List();
GLint GenPolycrankQ4List();
GLint GenPolycrankJointQ5Q4List();
GLint GenPolycrankQ5List();
GLint GenPolycrankJointQ6Q5List();
GLint GenPolycrankQ6List();
GLint GenPolycrankJointQ7Q6List();
GLint GenPolycrankQ7List();
GLint GenPolycrankQ8List();
GLint GenPolycrankFinger1List();
GLint GenPolycrankFinger2List();
